# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
#

exclude: ^$|config|imported_videos
fail_fast: false

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]


- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
