- https://kadist.org/people/abraham-cruzvillegas/
- https://kadist.org/people/abraham-oghobase/
- https://kadist.org/people/adriana-bustos/
- https://kadist.org/people/akira-takayama/
- https://kadist.org/people/asli-cavusoglu/
- https://kadist.org/people/aura-satz/
- https://kadist.org/people/bo-wang/
- https://kadist.org/people/carolina-caycedo/
- https://kadist.org/people/chloe-quenum/
- https://kadist.org/people/jes-fan/
- https://kadist.org/people/citra-sasmita/
- https://kadist.org/people/cynthia-gutierrez/
- https://kadist.org/people/danielle-dean/
- https://kadist.org/people/diamond-stingily/
- https://kadist.org/people/emilija-skarnulyte/
- https://kadist.org/people/finger-pointing-worker/
- https://kadist.org/people/hana-miletic/
- https://kadist.org/people/hikaru-fujii/
- https://kadist.org/people/hong-kai-wang/
- https://kadist.org/people/ho-rui-an/
- https://kadist.org/people/hulda-guzman/
- https://kadist.org/people/jakob-kudsk-steensen/
- https://kadist.org/people/la-decanatura/
- https://kadist.org/people/lin-ke/
- https://kadist.org/people/lola-gonzales/
- https://kadist.org/people/lynn-hershman-leeson/
- https://kadist.org/people/marie-voignier/
- https://kadist.org/people/marina-rosenfeld/
- https://kadist.org/people/matthew-angelo-harrison/
- https://kadist.org/people/melanie-matranga/
- https://kadist.org/people/milena-bonilla/
- https://kadist.org/people/minia-biabiany/
- https://kadist.org/people/natsuko-uchino/
- https://kadist.org/people/pedro-neves-marques/
- https://kadist.org/people/phan-thao-nguyen/
- https://kadist.org/people/pia-camil/
- https://kadist.org/people/pio-abad/
- https://kadist.org/people/randa-maddah/
- https://kadist.org/people/julia-rometti-victor-costales/
- https://kadist.org/people/samson-young/
- https://kadist.org/people/siren-eun-young-jung/
- https://kadist.org/people/tadasu-takamine/
- https://kadist.org/people/taus-makhacheva/
- https://kadist.org/people/thu-van-tran/
- https://kadist.org/people/uche-okpa-iroha/
- https://kadist.org/people/wang-tuo/
- https://kadist.org/people/ximena-garrido-lecca/
- https://kadist.org/people/ibro-hasanovic/
